twig:
  default_path: "%kernel.project_dir%/templates"
  globals:
    # PROD : To be updated
    pictures_directory: "%env(PICTURES_DIRECTORY)%"
    licenses_download_directory: "%env(LICENSES_DOWNLOAD_DIRECTORY)%"
    logo_teams_directory: "%env(LOGO_TEAMS_DIRECTORY)%"
  form_themes:
    - "@FOSCKEditor/Form/ckeditor_widget.html.twig"

when@test:
  twig:
    strict_variables: true
