twig:
  default_path: "%kernel.project_dir%/templates"
  globals:
    pictures_directory: "https://gihoul.be/clubhouse/public/uploads/user_pictures/"
    licenses_download_directory: "https://gihoul.be/clubhouse/public/licenses/download/"
    logo_teams_directory: "https://gihoul.be/clubhouse/public/uploads/logo_teams/"

when@test:
  twig:
    strict_variables: true
