# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  pictures_directory: "%kernel.project_dir%/public/uploads/user_pictures"
  logos_directory: "%kernel.project_dir%/public/uploads/logo_teams"
  uploaded_licenses_directory: "%kernel.project_dir%/public/uploads/licenses"
  env(PICTURES_DIRECTORY): ""
  env(LICENSES_DOWNLOAD_DIRECTORY): ""
  env(LOGO_TEAMS_DIRECTORY): ""

  locale: fr
  app_locales: "fr|en"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Service\LicensePDFGenerator:
    arguments:
      $pdfPath: "%kernel.project_dir%/public/licenses/source/"
      $outputPath: "%kernel.project_dir%/licenses/download/"

  App\Service\ProfilePictureManager:
    arguments:
      $fileUploader: '@App\Service\FileUploader'

  App\Controller\ErrorController:
    arguments: []

  App\Service\UnreadMessageCounter:
    arguments:
      $messageRepository: '@App\Repository\MessageRepository'

  App\Twig\UnreadMessagesExtension:
    arguments:
      $unreadMessageCounter: '@App\Service\UnreadMessageCounter'
    tags:
      - { name: twig.extension }
